feat: реализован функционал 8 спринта
3e54Ni7HTXo3Ds/java-filmorate pull request #1
Opened 2022-06-06 20:04 UTC by 3e54Ni7HTXo3Ds

2022-06-07 15:07 UTC, alexache requested changes
Работа очень хорошая, оставил немного комментариев по возможным улучшениям

2022-06-07 15:07 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +    private final HttpClient client = HttpClient.newHttpClient();
(молодец) Тесты несомненно круты, что проверяют всю связку, но в целом для данного задания можно было обойтись и тестом на сам контроллер без связки с HTTP ендпоинтам. Убирать конечно уже не нужно

2022-06-07 15:07 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +
Можно бы добавить тест на пустой объект User

2022-06-08 21:50 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            //, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE
Ок

2022-06-08 21:50 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validateFilm(film);
Ок

2022-06-08 21:50 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Ок

2022-06-08 21:50 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        }else if (film.getId() < 0) {
Ок

2022-06-08 21:51 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +    private final HttpClient client = HttpClient.newHttpClient();
Ок

2022-06-08 21:51 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +
Ок

2022-06-08 21:51 UTC, 3e54Ni7HTXo3Ds commented
По всем пунктам сделаны правки

2022-06-09 18:45 UTC, alexache approved these changes
Все ок

2022-06-09 18:45 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            users.remove(updateId);
(можно лучше) Такой же комментарий - можно обойтись просто с put() без remove

2022-06-09 18:45 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +        assertNotNull(response1, "��� ������");
Мне кажется или что-то случилось с кодировкой данного файла?

2022-06-13 19:09 UTC, merged