Add friends likes
3e54Ni7HTXo3Ds/java-filmorate pull request #2
Opened 2022-06-22 22:34 UTC by 3e54Ni7HTXo3Ds

реализован функционал 9 спринта

2022-06-23 21:32 UTC, alexache requested changes
Работа хорошая, но есть недочеты с валидацией данных, и разделения ответственности между контроллером, сервисом и стораджем

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
В контроллере все взаимодействие с сохраненными фильмами должно проходить через filmService, а не напрямую

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.findAllFilms();
Здесь и далее, где используется filmStorage, желательно использовать вызов сервиса вместо стораджа

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findPopular(count);
А что если count придет отрицательный или нулевой?

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getSortedFilms().remove(filmStorage.findFilmById(id));
А зачем удалять фильм для его изменения?
Объект тот же самый, почему просто не поменять его свойство?

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getSortedFilms().remove(filmStorage.findFilmById(id));
Тут тот же комментарий

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                sortedFilms.remove(findFilmById(film.getId()));
Зачем удалять, если можно просто заменить по ключу, как и делается в следующей строке

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            } else {
Нужно ли это разрешать?

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Здесь такой же комментарий - лучше не использовать storage в контроллере напрямую

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findUserById(userId).getFriends().add(friendId);
А что если такого id не существует? Или такого id friend?

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findUserById(userId).getFriends().remove(friendId);
И тут такой же вопрос - стоит валидировать

2022-06-23 21:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }
А иначе? Не нужно ли кидать эксепшен?

2022-06-25 08:29 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getSortedFilms().remove(filmStorage.findFilmById(id));
Объект хранится в treeset в отсортированном виде по количеству лайков. Соответственно если есть такой же объект он не может быть добавлен в treeset, так как уже там существует. Плюс при добавлении он проходит через компаратор и попадает на нужное место в сортировке, если лайки добавлены или удалены.

2022-06-25 08:30 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getSortedFilms().remove(filmStorage.findFilmById(id));
см коммент выше

2022-06-25 08:32 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            } else {
Если не ошибаюсь, это было в 8 спринте. Обновление если фильм существует и создание нового, если его не было.

2022-06-25 10:27 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Ок, исправлено

2022-06-25 10:27 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.findAllFilms();
Ок, исправлено

2022-06-25 10:27 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findPopular(count);
Ок, исправлено

2022-06-25 10:30 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                sortedFilms.remove(findFilmById(film.getId()));
см коммент выше, treeset при простом обновлении не пересчитывается и не дает добавить такой же объект

2022-06-25 10:31 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Ок, исправлено

2022-06-25 10:31 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findUserById(userId).getFriends().add(friendId);
Ок, исправлено

2022-06-25 10:31 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findUserById(userId).getFriends().remove(friendId);
Ок, исправлено

2022-06-25 10:31 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }
Ок, исправлено

2022-06-25 12:05 UTC, alexache approved these changes

2022-06-25 14:41 UTC, 3e54Ni7HTXo3Ds commented
Да, изменение количества лайков возможно через обновление фильма

2022-06-25 14:42 UTC, merged